#!/usr/bin/env python

'''
Device Monitor Daemon
'''

from uuid import uuid4

from gi.repository import GLib, GUdev

SESSION_ID = ''

def on_uevent(client, action, device):
    if action in ['add', 'remove', 'change']:
        dev_file = device.get_device_file()
        if dev_file:
            print('Spawning check')
            GLib.spawn_async(
                ['jockey-gtk', '--check', '-s', SESSION_ID],
                flags=GLib.SpawnFlags.SEARCH_PATH
            )

if __name__ == '__main__':
    # Generate a session id
    SESSION_ID = str(uuid4())
    loop = GLib.MainLoop()
    GLib.spawn_async(
        ['jockey-gtk', '--check', '-s', SESSION_ID],
        flags=GLib.SpawnFlags.SEARCH_PATH
    )
    client = GUdev.Client(subsystems=['pci', 'usb'])
    client.connect('uevent', on_uevent)
    loop.run()
